minio:
  image: minio/minio
  environment:
    MINIO_ROOT_USER: root
    MINIO_ROOT_PASSWORD: root1234
  command: server /data --console-address ":9001"
  volumes:
    - minio_data:/data
  ports:
    - '9000:9000'
    - '9001:9001'

volumes:
  minio_data:
